import { Poppins, Caveat } from "next/font/google";
import "./globals.css";

const poppins = Poppins ({
  weight: ["100", "200", "300", 
  "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

const caveat = Caveat ({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-caveat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${caveat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
